[package]
name = "gk-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
pretty_env_logger = "0.5.0"
tokio = { version = "1.27.0", features = ["full"] }
log = "0.4.17"
serde = { version= "1.0.171", features=['derive']}
serde_json = "1.0.102"
chrono = "0.4.26"
time = { version = "0.3.23", features = ["serde-well-known"] }
rust_decimal = { version = "1.30.0", features = ["serde-with-float"] }
rust_decimal_macros = "1.30.0"
diesel = { version = "2.1.0", features = ["mysql", "time"] }

dotenvy = "0.15"
tower = "0.4.13"
tower-http = { version = "0.4.1", features = ["cors", "trace", "add-extension", "sensitive-headers"] }
