name: Build and Publish Podman Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: jacksonrakena/gradekeeper-server
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile
    - name: Push image
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io
  
    - name: Print image URL  
      run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"
