name: Build and Publish Podman Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the image
      run: podman build -t ghcr.io/jacksonrakena/gradekeeper-server:latest .
    - name: Publish image
      run: podman push ghcr.io/jacksonrakena/gradekeeper-server:latest
